version: '3'
services:
  spring:
    image: maven:3-jdk-11-slim
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - 8080:8080
    command: mvn clean spring-boot:run
    restart: always
